services:
  postgres:
    image:  postgres:14-alpine
    container_name: postgres_muudal_14
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=muudal_user
      - POSTGRES_PASSWORD=muudal_password_123